// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package wasabi

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/codenow-com/pulumi-wasabi/sdk/go/wasabi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "wasabi:index/accessKey:AccessKey":
		r = &AccessKey{}
	case "wasabi:index/accountAlias:AccountAlias":
		r = &AccountAlias{}
	case "wasabi:index/accountPasswordPolicy:AccountPasswordPolicy":
		r = &AccountPasswordPolicy{}
	case "wasabi:index/bucket:Bucket":
		r = &Bucket{}
	case "wasabi:index/bucketObject:BucketObject":
		r = &BucketObject{}
	case "wasabi:index/bucketPolicy:BucketPolicy":
		r = &BucketPolicy{}
	case "wasabi:index/bucketPublicAccessBlock:BucketPublicAccessBlock":
		r = &BucketPublicAccessBlock{}
	case "wasabi:index/group:Group":
		r = &Group{}
	case "wasabi:index/groupMembership:GroupMembership":
		r = &GroupMembership{}
	case "wasabi:index/groupPolicy:GroupPolicy":
		r = &GroupPolicy{}
	case "wasabi:index/groupPolicyAttachment:GroupPolicyAttachment":
		r = &GroupPolicyAttachment{}
	case "wasabi:index/policy:Policy":
		r = &Policy{}
	case "wasabi:index/policyAttachment:PolicyAttachment":
		r = &PolicyAttachment{}
	case "wasabi:index/role:Role":
		r = &Role{}
	case "wasabi:index/rolePolicy:RolePolicy":
		r = &RolePolicy{}
	case "wasabi:index/rolePolicyAttachment:RolePolicyAttachment":
		r = &RolePolicyAttachment{}
	case "wasabi:index/user:User":
		r = &User{}
	case "wasabi:index/userGroupMembership:UserGroupMembership":
		r = &UserGroupMembership{}
	case "wasabi:index/userLoginProfile:UserLoginProfile":
		r = &UserLoginProfile{}
	case "wasabi:index/userPolicy:UserPolicy":
		r = &UserPolicy{}
	case "wasabi:index/userPolicyAttachment:UserPolicyAttachment":
		r = &UserPolicyAttachment{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:wasabi" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/accessKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/accountAlias",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/accountPasswordPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/bucket",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/bucketObject",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/bucketPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/bucketPublicAccessBlock",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/group",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/groupMembership",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/groupPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/groupPolicyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/policy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/policyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/rolePolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/rolePolicyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/userGroupMembership",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/userLoginProfile",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/userPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"wasabi",
		"index/userPolicyAttachment",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"wasabi",
		&pkg{version},
	)
}
