# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

accessKey: Optional[str]
"""
The access key for API operations. You can retrieve this from the 'Security & Credentials' section of the AWS console.
"""

allowedAccountIds: Optional[str]

assumeRole: Optional[str]

endpoints: Optional[str]

forbiddenAccountIds: Optional[str]

insecure: Optional[bool]
"""
Explicitly allow the provider to perform "insecure" SSL requests. If omitted,default value is `false`
"""

maxRetries: Optional[int]
"""
The maximum number of times an AWS API request is being executed. If the API request still fails, an error is thrown.
"""

profile: Optional[str]
"""
The profile for API operations. If not set, the default profile created with `aws configure` will be used.
"""

region: Optional[str]
"""
The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
"""

s3ForcePathStyle: Optional[bool]
"""
Set this to true to force the request to use path-style addressing, i.e., http://s3.amazonaws.com/BUCKET/KEY. By
default, the S3 client will use virtual hosted bucket addressing when possible (http://BUCKET.s3.amazonaws.com/KEY).
Specific to the Amazon S3 service.
"""

secretKey: Optional[str]
"""
The secret key for API operations. You can retrieve this from the 'Security & Credentials' section of the AWS console.
"""

sharedCredentialsFile: Optional[str]
"""
The path to the shared credentials file. If not set this defaults to ~/.aws/credentials.
"""

skipCredentialsValidation: Optional[bool]
"""
Skip the credentials validation via STS API. Used for AWS API implementations that do not have STS
available/implemented.
"""

skipMetadataApiCheck: Optional[bool]

skipRequestingAccountId: Optional[bool]
"""
Skip requesting the account ID. Used for AWS API implementations that do not have IAM/STS API and/or metadata API.
"""

token: Optional[str]
"""
session token. A session token is only required if you are using temporary security credentials.
"""

