# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .access_key import *
from .account_alias import *
from .account_password_policy import *
from .bucket import *
from .bucket_object import *
from .bucket_policy import *
from .bucket_public_access_block import *
from .get_account_alias import *
from .get_bucket import *
from .get_bucket_object import *
from .get_bucket_objects import *
from .get_group import *
from .get_policy import *
from .get_policy_document import *
from .get_role import *
from .get_user import *
from .group import *
from .group_membership import *
from .group_policy import *
from .group_policy_attachment import *
from .policy import *
from .policy_attachment import *
from .provider import *
from .role import *
from .role_policy import *
from .role_policy_attachment import *
from .user import *
from .user_group_membership import *
from .user_login_profile import *
from .user_policy import *
from .user_policy_attachment import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_wasabi.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_wasabi.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "wasabi",
  "mod": "index/accessKey",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/accessKey:AccessKey": "AccessKey"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/accountAlias",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/accountAlias:AccountAlias": "AccountAlias"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/accountPasswordPolicy",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/accountPasswordPolicy:AccountPasswordPolicy": "AccountPasswordPolicy"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/bucket",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/bucket:Bucket": "Bucket"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/bucketObject",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/bucketObject:BucketObject": "BucketObject"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/bucketPolicy",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/bucketPolicy:BucketPolicy": "BucketPolicy"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/bucketPublicAccessBlock",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/bucketPublicAccessBlock:BucketPublicAccessBlock": "BucketPublicAccessBlock"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/group",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/group:Group": "Group"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/groupMembership",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/groupMembership:GroupMembership": "GroupMembership"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/groupPolicy",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/groupPolicy:GroupPolicy": "GroupPolicy"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/groupPolicyAttachment",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/groupPolicyAttachment:GroupPolicyAttachment": "GroupPolicyAttachment"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/policy",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/policy:Policy": "Policy"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/policyAttachment",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/policyAttachment:PolicyAttachment": "PolicyAttachment"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/role",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/role:Role": "Role"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/rolePolicy",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/rolePolicy:RolePolicy": "RolePolicy"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/rolePolicyAttachment",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/rolePolicyAttachment:RolePolicyAttachment": "RolePolicyAttachment"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/user",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/user:User": "User"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/userGroupMembership",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/userGroupMembership:UserGroupMembership": "UserGroupMembership"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/userLoginProfile",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/userLoginProfile:UserLoginProfile": "UserLoginProfile"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/userPolicy",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/userPolicy:UserPolicy": "UserPolicy"
  }
 },
 {
  "pkg": "wasabi",
  "mod": "index/userPolicyAttachment",
  "fqn": "pulumi_wasabi",
  "classes": {
   "wasabi:index/userPolicyAttachment:UserPolicyAttachment": "UserPolicyAttachment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "wasabi",
  "token": "pulumi:providers:wasabi",
  "fqn": "pulumi_wasabi",
  "class": "Provider"
 }
]
"""
)
