// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wasabi.Inputs
{

    public sealed class ProviderEndpointArgs : global::Pulumi.ResourceArgs
    {
        [Input("iam")]
        public Input<string>? Iam { get; set; }

        [Input("s3")]
        public Input<string>? S3 { get; set; }

        [Input("sts")]
        public Input<string>? Sts { get; set; }

        public ProviderEndpointArgs()
        {
        }
        public static new ProviderEndpointArgs Empty => new ProviderEndpointArgs();
    }
}
