// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPolicyDocument(args?: GetPolicyDocumentArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyDocumentResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("wasabi:index/getPolicyDocument:getPolicyDocument", {
        "overrideJson": args.overrideJson,
        "policyId": args.policyId,
        "sourceJson": args.sourceJson,
        "statements": args.statements,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicyDocument.
 */
export interface GetPolicyDocumentArgs {
    overrideJson?: string;
    policyId?: string;
    sourceJson?: string;
    statements?: inputs.GetPolicyDocumentStatement[];
    version?: string;
}

/**
 * A collection of values returned by getPolicyDocument.
 */
export interface GetPolicyDocumentResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly json: string;
    readonly overrideJson?: string;
    readonly policyId?: string;
    readonly sourceJson?: string;
    readonly statements?: outputs.GetPolicyDocumentStatement[];
    readonly version?: string;
}
export function getPolicyDocumentOutput(args?: GetPolicyDocumentOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPolicyDocumentResult> {
    return pulumi.output(args).apply((a: any) => getPolicyDocument(a, opts))
}

/**
 * A collection of arguments for invoking getPolicyDocument.
 */
export interface GetPolicyDocumentOutputArgs {
    overrideJson?: pulumi.Input<string>;
    policyId?: pulumi.Input<string>;
    sourceJson?: pulumi.Input<string>;
    statements?: pulumi.Input<pulumi.Input<inputs.GetPolicyDocumentStatementArgs>[]>;
    version?: pulumi.Input<string>;
}
